server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bakgul24/ecommerce-config
          clone-on-start: true